apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: crud-server
  name: crud-server
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: crud-server
status:
  loadBalancer: {}
